"""
Generate `editor_build/src/tex_lexicon.mjs`: the word lists the code editor highlights,
completes and documents on hover, taken from the places that define the language.

    keywords            tex_compiler/lexer.py            KEYWORDS
    built-in variables  tex_compiler/type_checker.py     _BUILTIN_VAR_NAMES
    binding prefixes    tex_compiler/lexer.py            BINDING_TYPE_PREFIXES
    functions           the stdlib registry              help_entries() (name, sig, desc, aliases)

The editor bundle (`js/tex_cm6_bundle.js`) is built from this file by `npm run build` in
`editor_build/`, so a new stdlib function or keyword reaches the editor by running this
script and rebuilding. `tests/test_editor_bundle.py` fails when the committed file is
stale.

Run:  python tools/gen_editor_lexicon.py [--check]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.dirname(ROOT))  # custom_nodes on path

from TEX_Wrangle.tex_compiler.lexer import BINDING_TYPE_PREFIXES, KEYWORDS  # noqa: E402
from TEX_Wrangle.tex_compiler.type_checker import _BUILTIN_VAR_NAMES  # noqa: E402
from TEX_Wrangle.tex_runtime.stdlib import TEXStdlib  # noqa: E402,F401  (imported for its side effect: it populates REGISTRY)
from TEX_Wrangle.tex_runtime import stdlib_registry as R  # noqa: E402

_OUT = os.path.join(ROOT, "editor_build", "src", "tex_lexicon.mjs")

#: The built-in variables that are constants (highlighted as atoms, not as coordinates).
_CONSTANTS = ("PI", "TAU", "E")

_HEADER = """\
// GENERATED by tools/gen_editor_lexicon.py from the lexer, the type checker and the
// stdlib registry. Do not edit by hand: change the source and regenerate.
"""


def build():
    """The lexicon as plain data: word lists plus one [name, detail, info] row per function."""
    functions, aliases = [], []
    for e in R.help_entries(decode=True):
        name = e["name"]
        head = e["sig"].split(" → ")[0]
        if not head.startswith(name + "("):
            raise SystemExit(f"stdlib signature for {name!r} does not start with its call form: {e['sig']!r}")
        functions.append([name, head[len(name):], e["desc"]])
        aliases.extend([a, name] for a in e["aliases"])
    return {
        "LEX_KEYWORDS": list(KEYWORDS),
        "LEX_CONSTANTS": list(_CONSTANTS),
        "LEX_COORD_VARS": sorted(v for v in _BUILTIN_VAR_NAMES if v not in _CONSTANTS),
        "LEX_BINDING_PREFIXES": sorted(BINDING_TYPE_PREFIXES),
        "LEX_FUNCTIONS": functions,
        "LEX_ALIASES": aliases,
    }


def render(data) -> str:
    out = [_HEADER]
    for key, rows in data.items():
        if rows and isinstance(rows[0], list):
            body = ",\n".join("    " + json.dumps(r, ensure_ascii=True) for r in rows)
            out.append(f"export const {key} = [\n{body},\n];\n")
        else:
            out.append(f"export const {key} = {json.dumps(rows, ensure_ascii=True)};\n")
    return "\n".join(out)


def main():
    text = render(build())
    if "--check" in sys.argv:
        try:
            existing = open(_OUT, encoding="utf-8").read()
        except FileNotFoundError:
            print("tex_lexicon.mjs missing -- run tools/gen_editor_lexicon.py")
            return 1
        if existing.replace("\r\n", "\n") != text:
            print("tex_lexicon.mjs is stale -- regenerate with tools/gen_editor_lexicon.py")
            return 1
        print("tex_lexicon.mjs up to date")
        return 0
    with open(_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
